/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import dao.ClienteDAO;
import entity.Cliente;

/**
 *
 * @author weslley
 */
public class CadastroCliente1 extends javax.swing.JFrame {

    /**
     * Creates new form CadastroCliente1
     */
    public CadastroCliente1() {
        initComponents();
    }
 public void limpaTela() {
        // TODO add your handling code here:
        nomeCampo1.setText(null);
        enderecoCampo1.setText(null);
        emailCampo1.setText(null);
        telefoneCampo.setText(null);
        CPFCampo1.setText(null);
        senhaCampo1.setText(null);
        confirmarSenhaCampo1.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        senhaCampo1 = new javax.swing.JPasswordField();
        Criar1 = new javax.swing.JButton();
        confirmarSenhaCampo1 = new javax.swing.JPasswordField();
        Limpar1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cadastroTaxistaTexto1 = new javax.swing.JLabel();
        nomeCampo1 = new javax.swing.JTextField();
        enderecoCampo1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        telefoneCampo = new javax.swing.JTextField();
        try{ 
            javax.swing.text.MaskFormatter fone= new javax.swing.text.MaskFormatter("(##)#####-####"); 
            telefoneCampo = new javax.swing.JFormattedTextField(fone); 
        } 
        catch (Exception e){ 
        }
        emailCampo1 = new javax.swing.JTextField();
        Buscar1 = new javax.swing.JButton();
        nomeTexto1 = new javax.swing.JLabel();
        enderecoTexto1 = new javax.swing.JLabel();
        senhaTexto1 = new javax.swing.JLabel();
        telefoneTexto1 = new javax.swing.JLabel();
        confirmarSenhaTexto1 = new javax.swing.JLabel();
        emailTexto1 = new javax.swing.JLabel();
        observacao1 = new javax.swing.JLabel();
        placaTexto1 = new javax.swing.JLabel();
        CPFCampo1 = new javax.swing.JTextField();
        try{ 
            javax.swing.text.MaskFormatter doc= new javax.swing.text.MaskFormatter("###-###-###.##"); 
            CPFCampo1 = new javax.swing.JFormattedTextField(doc); 
        } 
        catch (Exception e){ 
        }

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Criar1.setText("Criar");
        Criar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Criar1ActionPerformed(evt);
            }
        });

        Limpar1.setText("Limpar");
        Limpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Limpar1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 153, 0));

        cadastroTaxistaTexto1.setBackground(new java.awt.Color(0, 102, 102));
        cadastroTaxistaTexto1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cadastroTaxistaTexto1.setText("Cadastro Cliente");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(cadastroTaxistaTexto1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(cadastroTaxistaTexto1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 153, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Programadores: Murilo Augusto, Ricardo Corassa, Weslley Martins e Edmar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(36, 36, 36))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 30, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        telefoneCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneCampoActionPerformed(evt);
            }
        });

        Buscar1.setText("Buscar");
        Buscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar1ActionPerformed(evt);
            }
        });

        nomeTexto1.setText("Nome:");

        enderecoTexto1.setText("Endereço:");

        senhaTexto1.setText("Senha:");

        telefoneTexto1.setText("Telefone:");

        confirmarSenhaTexto1.setText("Confirmar Senha:");

        emailTexto1.setText("E-mail:");

        observacao1.setText("obs: O CPF seré usado como usuário");

        placaTexto1.setText("CPF:");

        CPFCampo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPFCampo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 62, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(placaTexto1)
                                    .addComponent(emailTexto1)
                                    .addComponent(confirmarSenhaTexto1)
                                    .addComponent(senhaTexto1))
                                .addComponent(nomeTexto1)
                                .addComponent(enderecoTexto1))
                            .addComponent(telefoneTexto1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(observacao1)
                            .addComponent(senhaCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(CPFCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nomeCampo1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                    .addComponent(enderecoCampo1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                    .addComponent(emailCampo1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                    .addComponent(telefoneCampo, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                    .addComponent(confirmarSenhaCampo1))))
                        .addGap(179, 179, 179))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(Criar1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Limpar1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Buscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeCampo1, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(nomeTexto1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enderecoCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enderecoTexto1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(telefoneTexto1)
                    .addComponent(telefoneCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailTexto1))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CPFCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(placaTexto1))
                .addGap(10, 10, 10)
                .addComponent(observacao1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhaTexto1)
                    .addComponent(senhaCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmarSenhaTexto1)
                    .addComponent(confirmarSenhaCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Criar1)
                    .addComponent(Limpar1)
                    .addComponent(Buscar1))
                .addGap(81, 81, 81))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(445, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Criar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Criar1ActionPerformed
        ClienteDAO taxi = new ClienteDAO();
            Cliente cliente = new Cliente();
            cliente.setNome(nomeCampo1.getText());
            cliente.setEndereco(enderecoCampo1.getText());
            cliente.setTelefone(telefoneCampo.getText());
            cliente.setEmail(emailCampo1.getText());
            cliente.setCPF(CPFCampo1.getText());
            cliente.setSenha(senhaCampo1.getText());
            cliente.setConfirmarSenha(confirmarSenhaCampo1.getText());
            taxi.salvaBD(cliente);
            limpaTela();
    }//GEN-LAST:event_Criar1ActionPerformed

    private void Limpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Limpar1ActionPerformed
        // TODO add your handling code here
         limpaTela();
    }//GEN-LAST:event_Limpar1ActionPerformed

    private void telefoneCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneCampoActionPerformed

    private void Buscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar1ActionPerformed
        ConsultaCliente1 x = new ConsultaCliente1();
       x.setVisible(true);
    }//GEN-LAST:event_Buscar1ActionPerformed

    private void CPFCampo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPFCampo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CPFCampo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCliente1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar1;
    private javax.swing.JTextField CPFCampo1;
    private javax.swing.JButton Criar1;
    private javax.swing.JButton Limpar1;
    private javax.swing.JLabel cadastroTaxistaTexto1;
    private javax.swing.JPasswordField confirmarSenhaCampo1;
    private javax.swing.JLabel confirmarSenhaTexto1;
    private javax.swing.JTextField emailCampo1;
    private javax.swing.JLabel emailTexto1;
    private javax.swing.JTextField enderecoCampo1;
    private javax.swing.JLabel enderecoTexto1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField nomeCampo1;
    private javax.swing.JLabel nomeTexto1;
    private javax.swing.JLabel observacao1;
    private javax.swing.JLabel placaTexto1;
    private javax.swing.JPasswordField senhaCampo1;
    private javax.swing.JLabel senhaTexto1;
    private javax.swing.JTextField telefoneCampo;
    private javax.swing.JLabel telefoneTexto1;
    // End of variables declaration//GEN-END:variables
}
